name: Go presubmit

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: Go presubmit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.11', '1.12', '1.13', '1.14', '1.15']
    steps:
    - name: Install Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2
    - uses: creachadair/go-presubmit-action@default
